name: Test My Action

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run my custom action
        uses: ./    # Local path to action
        with:
          message: "Hello from GitHub Actions"
